set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" My Bundles here:
Plugin 'L9'
Plugin 'ctrlpvim/ctrlp.vim'
"撤销列表
Bundle 'sjl/gundo.vim' 
"自动配对
Bundle 'jiangmiao/auto-pairs'
Bundle 'klen/python-mode'
"语法检查
Bundle 'scrooloose/syntastic'
"目录树
Bundle 'scrooloose/nerdtree'
"tag
Bundle 'taglist.vim'
"winmanager
Bundle 'winmanager'
"power line
Bundle 'Lokaltog/vim-powerline'
"快速注释
Bundle 'scrooloose/nerdcommenter'
"buffer explorer
Bundle 'bufexplorer.zip'
" vim-scripts repos
"Bundle 'SudoEdit.vim'
"Bundle 'EasyGrep'
Bundle 'VOoM'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

syntax enable                " 打开语法高亮
syntax on                    " 开启文件类型侦测
set writebackup              " 设置无备份文件
set nobackup
set fileformats=unix,dos     " 行尾符
set autochdir                " 设定文件浏览器目录为当前目录
set nowrap                   " 设置不自动换行
set foldmethod=syntax        " 选择代码折叠类型
set foldlevel=100            " 禁止自动折叠
set guifont=Monaco:h10       " 字体 && 字号
set expandtab                " 设置tab键换空格
set tabstop=4                " 设置tab键的宽度
set shiftwidth=4             " 换行时行间交错使用4个空格
set autoindent               " 自动对齐
set backspace=2              " 设置退格键可用
set cindent shiftwidth=4     " 自动缩进4空格
set smartindent              " 智能自动缩进
set ai!                      " 设置自动缩进
set nu!                      " 显示行号
let g:SetNoToggleSwitch=1
set showmatch                " 显示括号配对情况
" set mouse=a                  " 启用鼠标
set ruler                    " 右下角显示光标位置的状态行
set incsearch                " 查找book时，当输入/b时会自动找到
set hlsearch                 " 开启高亮显示结果
set incsearch                " 开启实时搜索功能
set nowrapscan               " 搜索到文件两端时不重新搜索
set nocompatible             " 关闭兼容模式
set vb t_vb=                 " 关闭提示音
set cursorline               " 突出显示当前行
hi CursorLine  cterm=NONE   ctermbg=darkred ctermfg=white
hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white
set hidden                   " 允许在有未保存的修改时切换缓冲区

" 设置编码
set fenc=utf-8
set encoding=utf-8
set fileencodings=utf-8,gbk,cp936
" 解决consle输出乱码
language messages zh_CN.utf-8
" undo
nnoremap <F5> :GundoToggle<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Config Winmanager
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:winManagerWindowLayout="NERDTree|TagList|Bufxplorer"
let g:NERDTree_title="[NERDTree]"
let g:AutoOpenWinManager = 1

nmap <C-m> :WMToggle<CR>

function! NERDTree_Start()  
    exec 'NERDTree'  
endfunction

function! NERDTree_IsValid()  
    return 1  
endfunction

function SetNOToggle()  
    if g:SetNoToggleSwitch == 1
        exec 'set nonu'
        let g:SetNoToggleSwitch=0
    else
        exec 'set nu'
        let g:SetNoToggleSwitch=1
    endif
endfunction
nmap <C-l> :call SetNOToggle()<CR>

""""""""""""""""
" Config BufExplorer
""""""""""""""""
let g:bufExplorerDefaultHelp=0       " Do not show default help.
let g:bufExplorerShowRelativePath=1  " Show relative paths.
let g:bufExplorerSortBy='mru'        " Sort by most recently used.
let Tlist_File_Fold_Auto_Close=1     " 让当前不被编辑的文件的方法列表自动折叠起来
